export const contactList = [{
    id: 1,
    name: "papa",
    profilePic: "/profile/mapa.jpg",
    lastText: "where are you?",
    lastTextTime: "12:58 PM",
},
{
    id: 2,
    name: "Somu",
    profilePic: "/profile/somu.JPG",
    lastText: `what's going on `,
    lastTextTime: "12:45 PM",
},
{
    id: 3,
    name: "Mom",
    profilePic: "/profile/mapa.jpg",
    lastText: "How are you?",
    lastTextTime: "12:30 PM",
},
{
    id: 4,
    name: "sk",
    profilePic: "/profile/sk.jpg",
    lastText: "Hello",
    lastTextTime: "12:00 PM",
},
];
export const messagesList = [{
    id: 1,
    messageType: "TEXT",
    text: "hello",
    senderID: 0,
    addedOn: "12:00 PM",
},
{
    id: 2,
    messageType: "TEXT",
    text: "How are you?",
    senderID: 1,
    addedOn: "12:01 PM",
},
{
    id: 3,
    messageType: "TEXT",
    text: "I'm fine, What about you?",
    senderID: 0,
    addedOn: "12:00 PM",
},
{
    id: 4,
    messageType: "TEXT",
    text: "I'm good as well",
    senderID: 1,
    addedOn: "12:00 PM",
},
{
    id: 5,
    messageType: "TEXT",
    text: "Great to hear ",
    senderID: 0,
    addedOn: "12:00 PM",
},
{
    id: 5,
    messageType: "TEXT",
    text: "yeah",
    senderID: 1,
    addedOn: "12:00 PM",
},
];